# Generated by Django 4.1.7 on 2023-03-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Лого')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('adr_link', models.SlugField(verbose_name='Ссылка на карту')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('tel_num', models.CharField(max_length=55, verbose_name='Телефон')),
                ('facbook', models.SlugField(verbose_name='Фейсбук')),
                ('twitter', models.SlugField(verbose_name='Твиттер')),
                ('youtube', models.SlugField(verbose_name='Ютуб')),
                ('linkedin', models.SlugField(verbose_name='Линкедин')),
            ],
            options={
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
