# Generated by Django 4.1.7 on 2023-03-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='adr_link',
            field=models.CharField(max_length=255, verbose_name='Ссылка на карту'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='facbook',
            field=models.CharField(max_length=255, verbose_name='Фейсбук'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='linkedin',
            field=models.CharField(max_length=255, verbose_name='Линкедин'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twitter',
            field=models.CharField(max_length=255, verbose_name='Твиттер'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='youtube',
            field=models.CharField(max_length=255, verbose_name='Ютуб'),
        ),
    ]
