# Generated by Django 4.1.7 on 2023-03-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_settings_work_settings_work_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide/', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Слайд',
            },
        ),
    ]
