# Generated by Django 4.1.7 on 2023-03-18 17:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
