# Generated by Django 4.1.7 on 2023-03-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_slides_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/', verbose_name='Фото')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название услуги')),
                ('text', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
