# Generated by Django 4.1.7 on 2023-03-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='number',
            field=models.CharField(default='', max_length=15, verbose_name='Номер'),
        ),
    ]
