# Generated by Django 4.1.7 on 2023-03-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_remove_services_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.category'),
        ),
    ]
