# Generated by Django 4.1.7 on 2023-03-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_services_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
