# Generated by Django 4.1.7 on 2023-03-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_services_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Номер'),
        ),
    ]
