# Generated by Django 4.1.7 on 2023-03-18 22:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_services_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
