# Generated by Django 4.1.7 on 2023-03-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_category_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
