# Generated by Django 4.1.7 on 2023-03-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_delete_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
