# Generated by Django 4.1.7 on 2023-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_remove_projects_category_delete_projectimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ваше имя', max_length=155, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Email Address', max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
