# Generated by Django 4.1.7 on 2023-03-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_delete_services'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/', verbose_name='Фото')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название услуги')),
                ('text', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('number', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Номер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
