# Generated by Django 4.1.7 on 2023-03-21 18:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
