# Generated by Django 4.1.7 on 2023-03-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogs_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Блог'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Счет'),
        ),
    ]
