# Generated by Django 4.1.7 on 2023-03-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogs_options_blogs_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('comment', models.TextField(verbose_name='Коммент')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogs', verbose_name='Комменты')),
            ],
            options={
                'verbose_name_plural': 'Комменты',
            },
        ),
    ]
