# Generated by Django 4.1.7 on 2023-03-21 19:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0018_remove_projects_category_delete_projectimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
                ('main_image', models.ImageField(upload_to='project/', verbose_name='Фото')),
                ('client', models.CharField(max_length=255, verbose_name='Клиент')),
                ('date', models.DateField(verbose_name='Дата')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/', verbose_name='Фото')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name_plural': 'Фото проектов',
            },
        ),
    ]
