# Generated by Django 4.1.7 on 2023-03-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='desc',
        ),
        migrations.AddField(
            model_name='member',
            name='ex_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание опытов'),
        ),
        migrations.AddField(
            model_name='member',
            name='skill_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание скиллов'),
        ),
    ]
