# Generated by Django 4.1.7 on 2023-03-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_experience_desc_remove_skills_desc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='фейсбок'),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='инстаграм'),
        ),
        migrations.AddField(
            model_name='member',
            name='twitter',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Твиттер'),
        ),
    ]
