# Generated by Django 4.1.7 on 2023-03-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=15, verbose_name='Года')),
                ('name', models.CharField(max_length=255, verbose_name='Название событии')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='history/', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Наша история',
            },
        ),
    ]
