# Generated by Django 4.1.7 on 2023-03-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=155, verbose_name='Должность')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=255, verbose_name='Место')),
            ],
            options={
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
