# Generated by Django 4.1.7 on 2023-03-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Ф.И.О')),
                ('email', models.EmailField(max_length=254, verbose_name='email адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('post', models.CharField(max_length=155, verbose_name='Пост')),
                ('image', models.ImageField(upload_to='vacancy', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
