# Generated by Django 4.1.7 on 2023-03-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='image',
        ),
    ]
