# Generated by Django 4.1.7 on 2023-03-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_remove_apply_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='post',
        ),
    ]
