# Generated by Django 4.1.7 on 2023-03-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_remove_apply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='post',
            field=models.CharField(default=1, max_length=155, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
