# Generated by Django 4.1.7 on 2023-03-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_apply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='image',
            field=models.ImageField(default=1, upload_to='vacancy/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
